In [1]:
import pandas as pd 
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder 
from matplotlib import pyplot as plt


In [2]:
data = pd.read_csv("drug200.csv")

In [3]:
data.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [4]:
#Data Preprocessing 
data.describe()

Age     Na_to_K
count  200.000000  200.000000
mean    44.315000   16.084485
std     16.544315    7.223956
min     15.000000    6.269000
25%     31.000000   10.445500
50%     45.000000   13.936500
75%     58.000000   19.380000
max     74.000000   38.247000

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB


In [6]:
data.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [7]:
data["BP"].value_counts()


BP
HIGH      77
LOW       64
NORMAL    59
Name: count, dtype: int64

In [8]:
data["Sex"].value_counts()

Sex
M    104
F     96
Name: count, dtype: int64

In [9]:
data["Drug"].value_counts()

Drug
DrugY    91
drugX    54
drugA    23
drugC    16
drugB    16
Name: count, dtype: int64

In [10]:
le = LabelEncoder()
data.Sex= le.fit_transform(data.Sex)
data.BP = le.fit_transform(data.BP)
data.Cholesterol = le.fit_transform(data.Cholesterol)
data.Drug = le.fit_transform(data.Drug)

In [11]:
#Set features amd target variable 
x = data.drop("Drug",axis=1).values
y= data["Drug"].values

In [12]:
y

array([0, 3, 3, 4, 0, 4, 0, 3, 0, 0, 3, 0, 0, 0, 4, 0, 4, 1, 3, 0, 0, 0,
       0, 0, 0, 0, 0, 4, 0, 0, 4, 2, 4, 0, 4, 4, 1, 4, 4, 4, 0, 2, 0, 4,
       4, 4, 1, 3, 0, 0, 0, 4, 0, 0, 2, 3, 2, 0, 4, 0, 0, 1, 0, 4, 2, 0,
       1, 4, 0, 0, 2, 0, 4, 0, 0, 0, 1, 0, 1, 4, 2, 4, 3, 1, 3, 2, 4, 0,
       0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 1, 1, 3, 4, 0, 4, 4, 0, 2, 0,
       1, 4, 4, 4, 4, 0, 4, 4, 1, 0, 0, 0, 0, 0, 2, 0, 0, 4, 0, 4, 0, 0,
       4, 0, 0, 4, 2, 1, 2, 4, 1, 0, 2, 0, 1, 4, 4, 1, 4, 3, 1, 2, 4, 4,
       0, 3, 1, 0, 3, 4, 4, 2, 4, 0, 0, 0, 0, 4, 0, 1, 4, 4, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 4, 4, 0, 0, 0, 2, 1, 0, 0, 0, 1, 0, 3, 0, 3, 3, 4,
       4, 4])

In [13]:
x

array([[23.   ,  0.   ,  0.   ,  0.   , 25.355],
       [47.   ,  1.   ,  1.   ,  0.   , 13.093],
       [47.   ,  1.   ,  1.   ,  0.   , 10.114],
       [28.   ,  0.   ,  2.   ,  0.   ,  7.798],
       [61.   ,  0.   ,  1.   ,  0.   , 18.043],
       [22.   ,  0.   ,  2.   ,  0.   ,  8.607],
       [49.   ,  0.   ,  2.   ,  0.   , 16.275],
       [41.   ,  1.   ,  1.   ,  0.   , 11.037],
       [60.   ,  1.   ,  2.   ,  0.   , 15.171],
       [43.   ,  1.   ,  1.   ,  1.   , 19.368],
       [47.   ,  0.   ,  1.   ,  0.   , 11.767],
       [34.   ,  0.   ,  0.   ,  1.   , 19.199],
       [43.   ,  1.   ,  1.   ,  0.   , 15.376],
       [74.   ,  0.   ,  1.   ,  0.   , 20.942],
       [50.   ,  0.   ,  2.   ,  0.   , 12.703],
       [16.   ,  0.   ,  0.   ,  1.   , 15.516],
       [69.   ,  1.   ,  1.   ,  1.   , 11.455],
       [43.   ,  1.   ,  0.   ,  0.   , 13.972],
       [23.   ,  1.   ,  1.   ,  0.   ,  7.298],
       [32.   ,  0.   ,  0.   ,  1.   , 25.974],
       [57.   ,  1. 

In [14]:
#Feature scaling 
ss = StandardScaler()
x = ss.fit_transform(x)

In [15]:
#Spliting the data into training and testing
from sklearn.model_selection import train_test_split
from tensorflow import keras 

In [16]:
x_train,x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 42)

In [17]:
#converting features into float for model building 
Y_train = keras.utils.to_categorical(y_train)
Y_test = keras.utils.to_categorical(y_test)

In [18]:
#model building 
import tensorflow 
from tensorflow import keras 
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [25]:
model = Sequential()
model.add(Dense(12, input_dim = 5,activation = 'relu'))
model.add(Dense(24, activation = 'relu'))
model.add(Dense(36, activation = 'relu'))
model.add(Dense(5, activation = "softmax"))


In [26]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                      │ (None, 12)                  │              72 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 24)                  │             312 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ (None, 36)                  │             900 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 5)                   │             185 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,469 (5.74 KB)

 Trainable params: 1,469 (5.74 KB)

 Non-trainable params: 0 (0.00 B)

In [27]:
#compile the model 
model.compile(loss = "categorical_crossentropy",optimizer = 'adam', metrics = ["accuracy"])

In [28]:
#Train the model 
model.fit(x_train,Y_train, batch_size=10, epochs=20)

Epoch 1/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.2383 - loss: 1.6320
Epoch 2/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5173 - loss: 1.4803 
Epoch 3/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6630 - loss: 1.3454 
Epoch 4/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6076 - loss: 1.2349 
Epoch 5/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6640 - loss: 1.1231 
Epoch 6/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6430 - loss: 1.0740 
Epoch 7/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6822 - loss: 0.9642 
Epoch 8/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7141 - loss: 0.8204 
Epoch 9/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6889 - loss: 0.8118 
Epoch 10/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6964 - loss: 0.7469 
Epoch 11/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7167 - loss: 0.6979 
Epoch 12/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0

In [29]:
#test the accuracy 
loss, accuracy = model.evaluate(x_test, Y_test)
print("Accuracy is:", accuracy*100)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9125 - loss: 0.4426 
Accuracy is: 89.99999761581421


In [30]:
y_pred = model.predict(x_test)
y_pred

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step


array([[6.36839569e-02, 2.45045442e-02, 6.04516454e-03, 9.22996774e-02,
        8.13466668e-01],
       [7.33362794e-01, 1.20065607e-01, 6.49123043e-02, 6.05498292e-02,
        2.11094245e-02],
       [4.07657499e-04, 8.06862590e-05, 4.52919949e-06, 7.40210060e-03,
        9.92105007e-01],
       [4.43433486e-02, 2.44655177e-01, 7.48684034e-02, 3.66993845e-01,
        2.69139290e-01],
       [9.99968529e-01, 7.19644277e-06, 1.15431876e-05, 5.64680795e-06,
        7.04482409e-06],
       [6.19083643e-01, 1.09904476e-01, 2.36965373e-01, 3.09179872e-02,
        3.12857912e-03],
       [9.93315756e-01, 2.15229089e-03, 3.17726564e-03, 1.03923166e-03,
        3.15419893e-04],
       [3.12698409e-02, 1.10277045e-03, 1.45717029e-04, 6.29301295e-02,
        9.04551625e-01],
       [2.57052839e-01, 2.56962448e-01, 3.62734735e-01, 8.31901655e-02,
        4.00597341e-02],
       [1.21482287e-03, 2.11623585e-04, 1.37088091e-05, 5.07909525e-03,
        9.93480682e-01],
       [1.22348629e-01, 3.7191

In [34]:
#generating random input data 
num_sample = 5
#generating random data of the same shapes as input features 
random_input = np.random.rand(num_sample, x_train.shape[1])
#scaling the random input data 
random_input_scaled= ss.transform(random_input)
#predicting using the trained model 
prediction = model.predict(random_input_scaled)
#decode one-hot encoded predictions to get the predicted drug 
predicted_drug = [np.argmax(pred) for pred in prediction] 
#mapping predicted drug index to actual drug name 
drug_mapping = {0:"DrugA",1:"DrugB", 2:"DrugC", 3:"DrugX", 4:"DrugY"}
predicted_drugs_names = [drug_mapping[pred] for pred in predicted_drug]
#displaying the random input and predicted drugs 
print("Random Input data:")
print(random_input)
print("\nPredicted Drugs:")
print(predicted_drugs_names)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
Random Input data:
[[0.33829271 0.41066331 0.0847481  0.14666503 0.95365803]
 [0.70366658 0.54317371 0.45684483 0.98263701 0.07577221]
 [0.2997088  0.14188409 0.19671189 0.21136269 0.18902016]
 [0.51568926 0.27260926 0.35386008 0.2375773  0.90658078]
 [0.11476101 0.11859571 0.88480963 0.37098764 0.01995456]]

Predicted Drugs:
['DrugX', 'DrugY', 'DrugY', 'DrugY', 'DrugY']
